In [2]:
import pandas as pd

customers = pd.read_csv("customers_wk9_thurs.csv")

products = pd.read_csv("products_wk9_thurs.csv")

sales = pd.read_csv("sales_wk9_thurs.csv")

In [3]:
print("Customers:")

display(customers.head())

print("Products:")

display(products.head())

print("Sales:")

display(sales.head())

Customers:

,customer_id,first_name,last_name,age,state,income,registration_date,email
0,1,John,Smith,34,CA,75000,2022-01-15,john.smith@email.com
1,2,Sarah,Johnson,28,NY,82000,2022-01-22,sarah.johnson@email.com
2,3,Michael,Brown,45,TX,95000,2022-02-03,michael.brown@email.com
3,4,Emily,Davis,31,FL,68000,2022-02-14,emily.davis@email.com
4,5,David,Wilson,52,IL,110000,2022-02-28,david.wilson@email.com

Products:

,product_id,product_name,category,price,launch_date,brand
0,1,Wireless Bluetooth Headphones,Electronics,79.99,2021-03-15,AudioTech
1,2,Organic Cotton T-Shirt,Clothing,24.99,2021-04-20,EcoWear
2,3,Stainless Steel Water Bottle,Home & Garden,19.99,2021-05-10,HydroLife
3,4,Leather Crossbody Bag,Accessories,89.99,2021-06-01,StyleCraft
4,5,Yoga Mat Premium,Sports & Outdoors,34.99,2021-06-15,FitZone

Sales:

,sale_id,customer_id,product_id,transaction_date,quantity,total_amount
0,1,1,1,2022-02-10 14:30:00,1,79.99
1,2,2,3,2022-02-15 10:15:00,2,39.98
2,3,3,5,2022-02-20 16:45:00,1,34.99
3,4,4,2,2022-02-25 11:20:00,3,74.97
4,5,5,4,2022-03-01 13:10:00,1,89.99

In [4]:
# Convert all date columns to DateTime format

customers["registration_date"] = pd.to_datetime(customers["registration_date"])

products["launch_date"] = pd.to_datetime(products["launch_date"])

sales["transaction_date"] = pd.to_datetime(sales["transaction_date"])

In [5]:
# Extract useful date components from sales

sales["year"] = sales["transaction_date"].dt.year

sales["month"] = sales["transaction_date"].dt.month

sales["day_of_week"] = sales["transaction_date"].dt.day_name()

sales.head()

,sale_id,customer_id,product_id,transaction_date,quantity,total_amount,year,month,day_of_week
0,1,1,1,2022-02-10 14:30:00,1,79.99,2022,2,Thursday
1,2,2,3,2022-02-15 10:15:00,2,39.98,2022,2,Tuesday
2,3,3,5,2022-02-20 16:45:00,1,34.99,2022,2,Sunday
3,4,4,2,2022-02-25 11:20:00,3,74.97,2022,2,Friday
4,5,5,4,2022-03-01 13:10:00,1,89.99,2022,3,Tuesday

In [6]:
# Display the sales date range

print("Earliest sales date:", sales["transaction_date"].min())

print("Latest sales date:", sales["transaction_date"].max())

Earliest sales date: 2022-02-10 14:30:00
Latest sales date: 2024-03-05 10:30:00

In [7]:
# Basic time analysis

print("Busiest day of the week:")

display(sales["day_of_week"].value_counts())

print("Month with the most transactions:")

display(sales["month"].value_counts())

print("Number of sales in each year:")

display(sales["year"].value_counts().sort_index())

Busiest day of the week:

day_of_week
Friday       24
Tuesday      22
Thursday     21
Sunday       21
Saturday     21
Wednesday    21
Monday       20
Name: count, dtype: int64

Month with the most transactions:

month
2     16
3     14
12    14
4     12
5     12
6     12
7     12
8     12
9     12
10    12
11    12
1     10
Name: count, dtype: int64

Number of sales in each year:

year
2022    65
2023    72
2024    13
Name: count, dtype: int64

In [8]:
# Average product price by category

average_price_by_category = products.groupby("category")["price"].mean()

print("Average price by category:")

display(average_price_by_category)

Average price by category:

category
Accessories           35.073333
Clothing              52.240000
Electronics           59.990000
Home & Garden         30.156667
Sports & Outdoors    105.899091
Name: price, dtype: float64

In [9]:
# Number of products in each category

product_count_by_category = products.groupby("category")["product_id"].count()

print("Number of products by category:")

display(product_count_by_category)

Number of products by category:

category
Accessories          12
Clothing             12
Electronics          13
Home & Garden        12
Sports & Outdoors    11
Name: product_id, dtype: int64

In [10]:
# Average customer age in each state

average_age_by_state = customers.groupby("state")["age"].mean()

print("Average age by state:")

display(average_age_by_state)

Average age by state:

state
CA    34.10
FL    39.00
IL    37.25
NY    36.50
TX    38.30
Name: age, dtype: float64

In [11]:
# Total spending for each customer

customer_spending = sales.groupby("customer_id")["total_amount"].sum()

customer_spending = customer_spending.sort_values(ascending=False)

print("Total spending per customer:")

display(customer_spending)

Total spending per customer:

customer_id
31    379.97
13    359.96
41    329.98
84    319.98
30    284.98
       ...
70     33.98
89     29.99
69     28.99
72     24.99
77     12.99
Name: total_amount, Length: 90, dtype: float64

In [12]:
# Customers who made the most purchases

purchase_counts = sales.groupby("customer_id")["sale_id"].count()

purchase_counts = purchase_counts.sort_values(ascending=False)

print("Customers with the most purchases:")

display(purchase_counts.head(10))

Customers with the most purchases:

customer_id
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
Name: sale_id, dtype: int64

In [13]:
# Total sales revenue by month

monthly_revenue = sales.groupby("month")["total_amount"].sum()

print("Total sales revenue by month:")

display(monthly_revenue)

Total sales revenue by month:

month
1      864.79
2     1669.66
3     1115.77
4      924.77
5     1177.79
6      986.68
7      930.80
8      870.74
9     1150.76
10    1235.80
11    1022.76
12    1458.71
Name: total_amount, dtype: float64

In [14]:
# Average transaction amount by day of the week

average_transaction_by_day = (

    sales.groupby("day_of_week")["total_amount"]

    .mean()

    .sort_values(ascending=False)

)

print("Average transaction amount by day:")

display(average_transaction_by_day)

Average transaction amount by day:

day_of_week
Thursday     102.267619
Friday       100.940833
Sunday        99.551429
Wednesday     96.071905
Monday        90.927500
Tuesday       74.028636
Saturday      61.121905
Name: total_amount, dtype: float64

In [15]:
# Combine sales with product information

sales_products = sales.merge(

    products[["product_id", "category"]],

    on="product_id"

)

# Calculate total revenue by product category

category_revenue = (

    sales_products.groupby("category")["total_amount"]

    .sum()

    .sort_values(ascending=False)

)

print("Total revenue by product category:")

display(category_revenue)

print("\nHighest-revenue category:", category_revenue.idxmax())

Total revenue by product category:

category
Sports & Outdoors    3544.64
Electronics          3524.29
Clothing             2745.39
Accessories          2053.25
Home & Garden        1541.46
Name: total_amount, dtype: float64

Highest-revenue category: Sports & Outdoors

In [16]:
# Find the state with the most customers

customers_by_state = customers["state"].value_counts()

print("Number of customers by state:")

display(customers_by_state)

print("\nState with the most customers:", customers_by_state.idxmax())

Number of customers by state:

state
CA    20
NY    20
TX    20
FL    20
IL    20
Name: count, dtype: int64

State with the most customers: CA

In [17]:
# Identify the top 5 customers by total spending

top_5_customers = (

    customer_spending.head(5)

    .reset_index()

    .merge(

        customers[["customer_id", "first_name", "last_name"]],

        on="customer_id"

    )

)

top_5_customers["full_name"] = (

    top_5_customers["first_name"] + " " + top_5_customers["last_name"]

)

display(top_5_customers[["customer_id", "full_name", "total_amount"]])

   customer_id        full_name  total_amount
0           31  Daniel Gonzalez        379.97
1           13   Matthew Harris        359.96
2           41     Joseph Evans        329.98
3           84  Janice Gonzales        319.98
4           30   Kimberly Baker        284.98

In [18]:
# Determine the day with the highest average transaction value

average_transaction_by_day = (

    sales.groupby("day_of_week")["total_amount"]

    .mean()

    .sort_values(ascending=False)

)

print("Average transaction value by day:")

display(average_transaction_by_day)

print(

    "\nDay with the highest average transaction value:",

    average_transaction_by_day.idxmax()

)

Average transaction value by day:

day_of_week
Thursday     102.267619
Friday       100.940833
Sunday        99.551429
Wednesday     96.071905
Monday        90.927500
Tuesday       74.028636
Saturday      61.121905
Name: total_amount, dtype: float64

Day with the highest average transaction value: Thursday

## Discussion Questions

### 1. DateTime Benefits

Extracting the day of the week and month helps a retail business identify when customers shop most often. The business can use this information to plan staffing, inventory, promotions, and advertising around its busiest days and months.

### 2. GroupBy Value

Grouping data by categories, states, or time periods makes it easier to recognize patterns and compare performance. Instead of reviewing individual transactions, the business can quickly see which categories generate the most revenue, where most customers live, and when sales are strongest.

### 3. Business Applications

Based on the findings, the retail chain should consider increasing marketing and inventory for the Sports & Outdoors category because it generated the most revenue. The company could also run promotions during high-performing periods, focus on retaining its highest-spending customers, and examine why Thursday has the highest average transaction value.