In [1]:
import pandas as pd

customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
sales = pd.read_csv("sales.csv")
stores = pd.read_csv("stores.csv")
inventory = pd.read_csv("inventory.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'customers.csv'

In [2]:
import os

os.listdir()

['.ipynb_checkpoints',
 'bike_orders_database.sqlite',
 'customer_orders.csv',
 'data_sctructures_review.ipynb',
 'data_sctructures_review_sol.ipynb',
 'data_wrangling.ipynb',
 'data_wrangling_Solutions.ipynb',
 'Sales_Data.xlsx',
 'students.csv',
 'students_updated.csv',
 'subset_cols.png',
 'subset_iloc.png',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'wk8-customers (3).csv',
 'wk8-inventory (3).csv',
 'wk8-products (3).csv',
 'wk8-sales (3).csv',
 'wk8-stores (3).csv',
 'wk8_monday_exercise_canvas.ipynb']

In [3]:
import pandas as pd

customers = pd.read_csv("wk8-customers (3).csv")
products = pd.read_csv("wk8-products (3).csv")
sales = pd.read_csv("wk8-sales (3).csv")
stores = pd.read_csv("wk8-stores (3).csv")
inventory = pd.read_csv("wk8-inventory (3).csv")

In [4]:
display(customers.head())
display(products.head())
display(sales.head())
display(stores.head())
display(inventory.head())

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0

In [5]:
print("PRODUCTS SUMMARY")
display(products.describe())

print("SALES SUMMARY")
display(sales.describe())

print("INVENTORY SUMMARY")
display(inventory.describe())

PRODUCTS SUMMARY

       product_id        price         cost     weight
count   30.000000    30.000000    30.000000  28.000000
mean    15.500000   191.724000   203.159000   3.835714
std      8.803408   452.483576   278.924138   5.693236
min      1.000000 -1599.990000     1.800000   0.200000
25%      8.250000    46.990000    28.375000   0.500000
50%     15.500000   134.990000    82.500000   1.150000
75%     22.750000   322.490000   236.250000   3.750000
max     30.000000  1299.990000  1100.000000  25.000000

SALES SUMMARY

         sale_id   store_id  customer_id  product_id   quantity        total
count  40.000000  39.000000    40.000000   40.000000  40.000000    40.000000
mean   20.500000   6.487179    14.075000   13.500000   1.625000   352.296500
std    11.690452   4.235637     8.303189    8.857852   0.952392   377.625776
min     1.000000   1.000000     1.000000    1.000000   1.000000    19.980000
25%    10.750000   3.000000     6.750000    5.750000   1.000000    99.737500
50%    20.500000   6.000000    13.500000   11.500000   1.000000   229.985000
75%    30.250000   9.500000    20.250000   21.250000   2.000000   352.487500
max    40.000000  15.000000    29.000000   30.000000   5.000000  1599.990000

INVENTORY SUMMARY

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [8]:

print("INVENTORY SUMMARY")
display(inventory.describe())

INVENTORY SUMMARY

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [6]:
dataframes = {
    "Customers": customers,
    "Products": products,
    "Sales": sales,
    "Stores": stores,
    "Inventory": inventory
}

for name, df in dataframes.items():
    print(f"\n{name} missing values:")
    print(df.isnull().sum())

Customers missing values:
customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    3
dtype: int64

Products missing values:
product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          2
dtype: int64

Sales missing values:
sale_id           0
date              1
store_id          1
customer_id       0
product_id        0
quantity          0
total             0
payment_method    1
dtype: int64

Stores missing values:
store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       2
opening_date    1
dtype: int64

Inventory missing values:
inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    9
reorder_level        6
dtype: int64

In [7]:
for name, df in dataframes.items():
    print(f"\n{name} data types:")
    print(df.dtypes)

Customers data types:
customer_id          int64
first_name             str
last_name              str
email                  str
phone                  str
address                str
city                   str
state                  str
zip_code               str
registration_date      str
dtype: object

Products data types:
product_id        int64
product_name        str
category            str
subcategory         str
brand               str
price           float64
cost            float64
weight          float64
dtype: object

Sales data types:
sale_id             int64
date                  str
store_id          float64
customer_id         int64
product_id          int64
quantity            int64
total             float64
payment_method        str
dtype: object

Stores data types:
store_id          int64
store_name          str
address             str
city                str
state               str
zip_code            str
region              str
size_sqft       float64
opening_date        str
dtype: object

Inventory data types:
inventory_id           int64
store_id               int64
product_id             int64
quantity_in_stock      int64
last_restock_date        str
reorder_level        float64
dtype: object

In [9]:
# Number of unique products
unique_products = products["product_id"].nunique()
print("Number of unique products:", unique_products)

Number of unique products: 30

In [10]:
# Top 5 most expensive products
top_5_expensive = products.nlargest(
    5,
    "price"
)[["product_name", "price"]]

print("Top 5 most expensive products:")
display(top_5_expensive)

Top 5 most expensive products:

          product_name    price
3          Dell XPS 13  1299.99
0      Apple iPhone 13   899.99
1   Samsung Galaxy S21   799.99
19    Dyson V11 Vacuum   599.99
26  Sony PlayStation 5   499.99

In [11]:
# Store with the largest floor space
largest_store = stores.loc[
    stores["size_sqft"].idxmax(),
    ["store_name", "city", "state", "size_sqft"]
]

print("Store with the largest floor space:")
display(largest_store)

Store with the largest floor space:

store_name    Los Angeles Plaza
city                Los Angeles
state                        CA
size_sqft               55000.0
Name: 2, dtype: object

In [12]:
# Distribution of customers by state
customer_state_distribution = customers["state"].value_counts()

print("Customer distribution by state:")
display(customer_state_distribution)

Customer distribution by state:

state
TX                4
CA                3
NY                2
California        1
IL                1
AZ                1
PA                1
Texas             1
FL                1
OH                1
North Carolina    1
IN                1
Washington        1
CO                1
MA                1
Oregon            1
NV                1
MI                1
TN                1
Maryland          1
MD                1
KY                1
WI                1
NM                1
MO                1
Name: count, dtype: int64

In [13]:
# Convert date columns to datetime
for name, df in dataframes.items():
    date_columns = [
        column for column in df.columns
        if "date" in column.lower()
    ]

    for column in date_columns:
        df[column] = pd.to_datetime(df[column], errors="coerce")
        df[column] = df[column].ffill().bfill()

In [14]:
for name, df in dataframes.items():

    # Replace missing numerical values with the column mean
    numerical_columns = df.select_dtypes(include="number").columns

    for column in numerical_columns:
        df[column] = df[column].fillna(df[column].mean())

    # Replace missing categorical values with the most frequent value
    categorical_columns = df.select_dtypes(
        include=["object", "category"]
    ).columns

    for column in categorical_columns:
        if not df[column].mode().empty:
            df[column] = df[column].fillna(df[column].mode()[0])

C:\Users\Jacly\AppData\Local\Temp\ipykernel_2660\1468725097.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\Jacly\AppData\Local\Temp\ipykernel_2660\1468725097.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\Jacly\AppData\Local\Temp\ipykernel_2660\1468725097.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\Jacly\AppData\Local\Temp\ipykernel_2660\1468725097.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [15]:
for name, df in dataframes.items():
    print(f"\n{name} missing values after cleaning:")
    print(df.isnull().sum())

Customers missing values after cleaning:
customer_id          0
first_name           0
last_name            0
email                0
phone                0
address              0
city                 0
state                0
zip_code             0
registration_date    0
dtype: int64

Products missing values after cleaning:
product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          0
dtype: int64

Sales missing values after cleaning:
sale_id           0
date              0
store_id          0
customer_id       0
product_id        0
quantity          0
total             0
payment_method    0
dtype: int64

Stores missing values after cleaning:
store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       0
opening_date    0
dtype: int64

Inventory missing values after cleaning:
inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    0
reorder_level        0
dtype: int64

In [16]:
print("Customer duplicates before cleaning:", customers.duplicated().sum())
print("Product duplicates before cleaning:", products.duplicated().sum())

customers = customers.drop_duplicates().reset_index(drop=True)
products = products.drop_duplicates().reset_index(drop=True)

print("Customer duplicates after cleaning:", customers.duplicated().sum())
print("Product duplicates after cleaning:", products.duplicated().sum())

Customer duplicates before cleaning: 0
Product duplicates before cleaning: 0
Customer duplicates after cleaning: 0
Product duplicates after cleaning: 0

## Discussion Questions

### 1. What are the key advantages of using Pandas for data cleaning?

Pandas makes it easy to inspect, filter, transform, and clean large datasets using concise Python code. It includes built-in methods for handling missing values, duplicates, incorrect data types, and summary statistics. The cleaning steps can also be repeated consistently.

### 2. How would handling missing values differ if the missing data had a pattern or meaning?

I would first investigate why the values were missing instead of automatically replacing them. If the missing data represented a meaningful customer behavior or business condition, I might create a separate missing-value category or indicator column to preserve that information.

### 3. What data-quality issues might not be visible through simple DataFrame inspection?

Potential issues include inconsistent spelling, incorrect values that still fall within a valid range, mismatched identifiers between datasets, inaccurate dates, formatting differences, hidden whitespace, and duplicate records that are not completely identical.

### 4. How would you document the cleaning process for reproducibility?

I would keep each cleaning step in an organized Jupyter notebook with Markdown explanations, comments, and clearly named variables. I would preserve the original data, record any assumptions, and save the cleaned results separately so another analyst could repeat the process.

### 5. When might it be better to remove rows with missing values?

Removing rows may be appropriate when only a small percentage of records are missing, when the missing values affect essential fields, or when imputing values could introduce bias or misleading information. It is most appropriate when removing the rows will not significantly reduce the dataset or distort the analysis.